const ordlisteKategorier = {
    // === VOKALER OG DIFTANGER ===
    "bolk1": {
        "Enkel vokal (a, e, i, o, u, y, æ, ø, å)": [
            { ord: "glad", lengde: 4, setning: "Gutten ble kjempe___ da han fikk en ny leke." },
            { ord: "lese", lengde: 4, setning: "Vi skal ___ en spennende bok i timen." },
            { ord: "fisk", lengde: 4, setning: "Det svømte en liten, rød ___ i vannet." },
            { ord: "sol", lengde: 3, setning: "I dag skinner en varm ___ på himmelen." },
            { ord: "hus", lengde: 3, setning: "Vi bor i et gult ___ med hage." },
            { ord: "mye", lengde: 4, setning: "Det var ___ snø ute på bakken." },
            { ord: "tre", lengde: 3, setning: "Fuglen satt høyt oppe i et stort ___." },
            { ord: "snø", lengde: 3, setning: "Det falt hvit ___ fra himmelen i natt." },
            { ord: "båt", lengde: 3, setning: "Vi seilte ut på fjorden i en liten ___." },
            { ord: "katt", lengde: 4, setning: "Vår ___ liker å sitte i vinduet og se ut." },
            { ord: "melk", lengde: 4, setning: "Jeg drikker et glass kald ___ til maten." },
            { ord: "bil", lengde: 3, setning: "Pappa kjører en rød ___ til jobben." },
            { ord: "ost", lengde: 3, setning: "Musa likte veldig godt å spise ___." },
            { ord: "gull", lengde: 4, setning: "Kongen bar en krone laget av ___." },
            { ord: "sykkel", lengde: 6, setning: "Hun fikk en ny, flott ___ til bursdagen sin." },
            { ord: "sæter", lengde: 5, setning: "Kuene gikk opp på en grønn ___ i sommer." },
            { ord: "pølse", lengde: 5, setning: "Vi grillet god ___ på bålet i skogen." },
            { ord: "blå", lengde: 3, setning: "Himmelen var helt ___ og uten skyer." },
            { ord: "tak", lengde: 3, setning: "Katten klatret helt opp på husets ___." },
            { ord: "venn", lengde: 4, setning: "Det er koselig å leke med sin beste ___." },
            { ord: "is", lengde: 2, setning: "Det er godt å spise kald ___ om sommeren." },
            { ord: "bok", lengde: 3, setning: "Læreren åpnet en ny ___ for å lese høyt." },
            { ord: "buss", lengde: 4, setning: "Vi tok en stor, gul ___ til skolen." },
            { ord: "lyve", lengde: 4, setning: "Det er viktig å tale sant og aldri ___." },
            { ord: "bær", lengde: 3, setning: "Vi plukket søte, røde ___ i skogen." },
            { ord: "øye", lengde: 3, setning: "Hun fikk et lite rusk i sitt høyre ___." },
            { ord: "grå", lengde: 3, setning: "Skyen på himmelen var mørk og ___." },
            { ord: "kake", lengde: 4, setning: "Mamma bakte en kjempegod ___ til festen." },
            { ord: "regn", lengde: 4, setning: "Det falt mykje ___ fra skyene i dag." },
            { ord: "sitt", lengde: 4, setning: "Barnet tegnet et hus på arket ___." },
            { ord: "sopp", lengde: 4, setning: "Vi fant en rød og hvit ___ i skogen." },
            { ord: "tur", lengde: 3, setning: "Hver søndag går vi en lang ___ i marka." },
            { ord: "sky", lengde: 3, setning: "Det var ikke en eneste ___ å se på himmelen." },
            { ord: "knær", lengde: 4, setning: "Gutten falt og slo begge sine ___." },
            { ord: "mål", lengde: 3, setning: "Fotballspilleren skjøt ballen rett i ___." },
            { ord: "lås", lengde: 3, setning: "Husk å sette en god ___ på sykkelen din." }
        ],
        "Diftanger (ai, au, ei, øy)": [
            { ord: "hai", lengde: 3, setning: "En stor ___ svømte rolig dypt nede i havet." },
            { ord: "kai", lengde: 3, setning: "Båten la trygt til ved en gammel ___." },
            { ord: "papegøye", lengde: 8, setning: "I jungelen så vi en fargerik og staselig ___." },
            { ord: "sau", lengde: 3, setning: "En hvit ___ gikk og spiste gress på jordet." },
            { ord: "reinsdyr", lengde: 8, setning: "I fjellet så vi et staselig ___ med store horn." },
            { ord: "stein", lengde: 5, setning: "Han kastet en liten ___ ut i det blikkstille vannet." },
            { ord: "speil", lengde: 5, setning: "Jenta så seg i sitt eget ___ på badet." },
            { ord: "reise", lengde: 5, setning: "I sommerferien skal familien ___ på tur med fly." },
            { ord: "teip", lengde: 4, setning: "Mamma brukte litt ___ til å pakke inn den fine gaven." },
            { ord: "fløyte", lengde: 6, setning: "Han spilte en lys og vakker tone på sin ___." },
            { ord: "øye", lengde: 3, setning: "Katten blunket forsiktig med det ene ___ sitt." },
            { ord: "røyke", lengde: 5, setning: "Det begynte å ___ kraftig fra det svidde bålet." },
            { ord: "skøyter", lengde: 7, setning: "Om vinteren gikk vi på ___ utpå den frosne isen." },
            { ord: "maur", lengde: 4, setning: "En flittig liten ___ bar et barål på ryggen." },
            { ord: "tausc", lengde: 5, setning: "Han var helt ___ og sa ikke et eneste ord." },
            { ord: "pause", lengde: 5, setning: "Det var deilig å ta en liten ___ etter løpeturen." },
            { ord: "gaupe", lengde: 5, setning: "En folkesky ___ snek seg lydløst gjennom skogen." },
            { ord: "fløy", lengde: 4, setning: "En vakker fugl ___ høyt over de grønne trærne." },
            { ord: "leik", lengde: 4, setning: "Barna var i full ___ ute på lekeplassen." },
            { ord: "vei", lengde: 3, setning: "Vi gikk på en koselig ___ gjennom skogen." }
        ]
    },

    // === DOBBELTKONSONANT ===
    "bolk2": {
        "Enkel vs dobbeltkonsonanter": [
            { ord: "tak", lengde: 3, setning: "Mannen klatret opp på sitt eget ___." },
            { ord: "takk", lengde: 4, setning: "Husk å si fint ___ for maten du fikk." },
            { ord: "hat", lengde: 3, setning: "Krig skaper tydeleg ___ og sinne mellom folk." },
            { ord: "hatt", lengde: 4, setning: "Bestefar hadde en stilig, svart ___ på hodet." },
            { ord: "mat", lengde: 3, setning: "Vi må spise god og sunn ___ hver dag." },
            { ord: "matt", lengde: 4, setning: "Sjakkspilleren satte motstanderen sjakklag og ___." },
            { ord: "pen", lengde: 3, setning: "Hun hadde på seg en veldig ___ kjole til festen." },
            { ord: "penn", lengde: 4, setning: "Læreren skrev en rettelse med en rød ___." },
            { ord: "sot", lengde: 3, setning: "Feieren ble helt svart av ___ fra pipa." },
            { ord: "sott", lengde: 4, setning: "I gamle dager ble mange syke av en fæl ___." },
            { ord: "man", lengde: 3, setning: "Hesten hadde en lang og vakker ___." },
            { ord: "mann", lengde: 4, setning: "En hyggelig ___ stoppet for å vise oss veien." },
            { ord: "bak", lengde: 3, setning: "Hunden gjemte seg trygt ___ den store sofaen." },
            { ord: "bakk", lengde: 4, setning: "Kapteinen ba mannskapet slå ___ på skipet." },
            { ord: "skal", lengde: 4, setning: "Barna ___ snart ut for å leke i friminuttet." },
            { ord: "skall", lengde: 5, setning: "Kyllingen hakket et hull i eggets harde ___." },
            { ord: "vel", lengde: 3, setning: "Du blir ___ med på leken uti friminuttet?" },
            { ord: "vell", lengde: 4, setning: "Et utømmelig ___ av vann rant fra kilden." },
            { ord: "vil", lengde: 3, setning: "Jeg ___ gjerne ha et lite stykke til med kake." },
            { ord: "vill", lengde: 4, setning: "En skummel og ___ ulv løp gjennom skogen." }
        ],
        "Standard dobbeltkonsonanter": [
            { ord: "hoppe", lengde: 5, setning: "Det er kjempegøy å ___ på trampolinen i hagen." },
            { ord: "katte", lengde: 5, setning: "En søt liten ___pus lå og sov på matta." },
            { ord: "spille", lengde: 6, setning: "Vi liker å ___ fotball sammen i friminuttet." },
            { ord: "rekke", lengde: 5, setning: "Du må huske å ___ opp hånden hvis du vil si noe." },
            { ord: "dokke", lengde: 5, setning: "Jenta lekte pent med sin nye ___ i dag." },
            { ord: "rekke", lengde: 5, setning: "Vi må skynde oss så vi skal ___ bussen." },
            { ord: "bolle", lengde: 5, setning: "Mamma bakte en nystekt og varm ___ med hvetemel." },
            { ord: "rulle", lengde: 5, setning: "Ballen begynte å ___ rolig nedover den bratte bakken." },
            { ord: "ligge", lengde: 5, setning: "Det er deilig å ___ på gresset og se på skyene." },
            { ord: "mamma", lengde: 5, setning: "Jeg ga min snille ___ en god og varm klem." },
            { ord: "pappa", lengde: 5, setning: "Min ___ er flink til å hjelpe meg med leksene min." },
            { ord: "klasse", lengde: 6, setning: "Det er mange hyggelige elever i min ___." },
            { ord: "kaste", lengde: 5, setning: "Guttungen liker å ___ ballen så langt han klarer." },
            { ord: "sitte", lengde: 5, setning: "Alle elever må ___ rolig på stolene sine." },
            { ord: "finne", lengde: 5, setning: "Klarer du å ___ igjen din mistede vott?" },
            { ord: "svømme", lengde: 6, setning: "Om sommeren er det herlig å ___ i det varme vannet." },
            { ord: "felle", lengde: 5, setning: "Musa gikk rett i fella som var lagt ut." },
            { ord: "lukke", lengde: 5, setning: "Husk å ___ døra ordentlig når du går ut." },
            { ord: "pakke", lengde: 5, setning: "Jeg fikk en kjempefin ___ til bursdagen min." },
            { ord: "rekke", lengde: 5, setning: "En lang ___ med biler sto i kø på veien." }
        ]
    },

    // === SPESIELLE KONSONANTSAMMENSETNINGER ===
    "bolk3": {
        "Sammensatte lyder (ng, nk, sj, skj, kj)": [
            { ord: "mange", lengde: 5, setning: "Det var ___ barna som lekte ute på den grønne plassen." },
            { ord: "synge", lengde: 5, setning: "Koret skal ___ en fin sang i kirken på søndag." },
            { ord: "banke", lengde: 5, setning: "Husk å ___ forsiktig på døra før du går inn." },
            { ord: "tenke", lengde: 5, setning: "Nå må vi ___ oss om for å finne svar på oppgaven." },
            { ord: "sjokolade", lengde: 9, setning: "Vi spiste god mørk ___ til kos på lørdag." },
            { ord: "sjanse", lengde: 6, setning: "Han fikk en ny ___ til å prøve å kaste ballen." },
            { ord: "skjorte", lengde: 7, setning: "Pappa strøk en fin hvit ___ før festen." },
            { ord: "skjegg", lengde: 6, setning: "Bestefar har et stort, hvit og flott ___." },
            { ord: "kjøre", lengde: 5, setning: "Det var gøy å ___ fort på akebrettet i snøen." },
            { ord: "kjøkken", lengde: 7, setning: "Mamma lager nydelig mat inne på vårt ___." },
            { ord: "sjø", lengde: 3, setning: "Vi så mange båter som seilte ut på den store ___en." },
            { ord: "kjøtt", lengde: 5, setning: "Til middag spiste vi god saus og ___boller." },
            { ord: "skje", lengde: 4, setning: "Jeg spiste den gode suppen min med en stor ___." },
            { ord: "skjære", lengde: 6, setning: "Pappa må bruke en skarp kniv til å ___ brødet." },
            { ord: "kjole", lengde: 5, setning: "Jenta pyntet seg i en rød ___ til festen." },
            { ord: "kjekk", lengde: 5, setning: "Han var en veldig snill og ___ gutt i klassen." },
            { ord: "gang", lengde: 4, setning: "Dette var den første ___en jeg prøvde å gå på skøyter." },
            { ord: "tanke", lengde: 5, setning: "Jeg fikk en veldig god ___ til hvordan vi kan løse dette." },
            { ord: "sjef", lengde: 4, setning: "Kapteinen var ___ på det store skipet." },
            { ord: "skjerm", lengde: 6, setning: "Vi så en fin film på en stor ___ i kinosalen." }
        ]
    },

    // === KONSONANTLYDER (KJ, SJ, J, KI/KY, SKI/SKY) ===
    "bolk4": {
        "kj-lyd": [
            { ord: "kjekk", lengde: 5, setning: "Han var en veldig morsom og ___ gutt." },
            { ord: "kjøpe", lengde: 5, setning: "Vi skal dra til butikken for å ___ is." },
            { ord: "kjerre", lengde: 6, setning: "Hesten trakk en gammel ___ full av høy." },
            { ord: "kjøtt", lengde: 5, setning: "Til middag spiste vi ___boller og poteter." },
            { ord: "kjøkken", lengde: 7, setning: "Mamma og pappa lager god mat på våres ___." },
            { ord: "kjøre", lengde: 5, setning: "Det er gøy å ___ fort på akebrettet." },
            { ord: "kjenne", lengde: 6, setning: "Det er koselig å ___ at solen varmer i ansiktet." },
            { ord: "kjeller", lengde: 7, setning: "Vi gjemte oss nede i en mørk ___." },
            { ord: "kjepp", lengde: 5, setning: "Hunden løp etter en lang ___ som jeg kastet." },
            { ord: "kjole", lengde: 5, setning: "Hun pyntet seg med en rød ___ til bursdagen." },
            { ord: "kirke", lengde: 5, setning: "Klokkene ringte høyt fra en gammel ___." },
            { ord: "kitt", lengde: 4, setning: "Glassmesteren brukte ___ til å feste vindusruten." },
            { ord: "kyst", lengde: 4, setning: "Det blåste en frisk vind langs norges ___." },
            { ord: "kjære", lengde: 5, setning: "Min ___ bestemor baker verdens beste boller." },
            { ord: "kiste", lengde: 5, setning: "Sjørøverne gjemte gullet i en stor ___ av tre." },
            { ord: "kjevene", lengde: 7, setning: "Løven åpnet de store ___ sine og gjespet høyt." },
            { ord: "kinn", lengde: 4, setning: "Jenta ble varm og rød på hvert ___ etter løpet." },
            { ord: "kjeks", lengde: 5, setning: "Vi fikk lov til å spise en sprø ___ til frukten." },
            { ord: "kjempe", lengde: 6, setning: "I eventyret møtte riddersmannen en stor ___." },
            { ord: "kilo", lengde: 4, setning: "En stor pose med poteter veide nøyaktig to ___." },
            { ord: "kyse", lengde: 4, setning: "Den vesle babyen hadde en hvit ___ knyttet under haken." },
            { ord: "kikker", lengde: 6, setning: "Fugletitteren ___ spent opp i det høye treet." },
            { ord: "kilen", lengde: 5, setning: "Gutten lo høyt fordi han var så ___ under føttene." },
            { ord: "kylling", lengde: 7, setning: "Ut av egget kom det en liten, gul ___." }
        ],
        "sj-lyd": [
            { ord: "skje", lengde: 4, setning: "Jeg spiste suppen min med en stor ___." },
            { ord: "skjegg", lengde: 6, setning: "Bestefar har et veldig langt og hvitt ___." },
            { ord: "skjorte", lengde: 7, setning: "Pappa strøk en fin, hvit ___ til festen." },
            { ord: "skjerf", lengde: 6, setning: "Om vinteren må vi bruke et varmt ___ rundt halsen." },
            { ord: "skjære", lengde: 6, setning: "Vi må bruke en kniv til å ___ opp brødet." },
            { ord: "skjelve", lengde: 7, setning: "Kulden i vannet fikk ham til å ___." },
            { ord: "skjørt", lengde: 6, setning: "Jenta snurret rundt i sitt nye ___." },
            { ord: "skjerm", lengde: 6, setning: "Lyset skinte lyst fra en datamaskin-___." },
            { ord: "skjell", lengde: 6, setning: "Barna fann et vakkert ___ på den sandete stranda." },
            { ord: "skjenne", lengde: 7, setning: "De voksne må av og til ___ hvis vi gjør noe farlig." },
            { ord: "sjanse", lengde: 6, setning: "Fotballspilleren fikk en stor ___ til å score mål." },
            { ord: "sjef", lengde: 4, setning: "Kapteinen er den som bestemmer og er ___ på skipet." },
            { ord: "skjul", lengde: 5, setning: "Barna lekte gjemsel og fant et godt ___ bak hekken." },
            { ord: "sjel", lengde: 4, setning: "Han sang en vakker sang med både ___ og varme." },
            { ord: "sju", lengde: 3, setning: "En uke har nøyaktig ___ dager i seg." },
            { ord: "sjokk", lengde: 5, setning: "Det kom som et stort ___ at det plutselig begynte å hagle." },
            { ord: "sjakk", lengde: 5, setning: "Bestefar lærte meg å spille ___ på det rutete brettet." },
            { ord: "sjekte", lengde: 6, setning: "Vi tøffet rolig ut på fjorden i en koselig ___." },
            { ord: "sjette", lengde: 6, setning: "Hun kom på ___ plass i det spennende sykkelløpet." },
            { ord: "skjold", lengde: 6, setning: "Ridderen beskyttet seg mot pilene med et tungt ___." },
            { ord: "sjelden", lengde: 7, setning: "En firkløver i gresset er et ganske ___ funn." },
            { ord: "sjuk", lengde: 4, setning: "Han måtte holde senga i dag fordi han var blitt ___." },
            { ord: "sjal", lengde: 4, setning: "Bestemor la et mykt ___ over skuldrene sine." },
            { ord: "sjekk", lengde: 5, setning: "Ta en ekstra ___ i sekken din for å se om boka ligger der." },
            { ord: "skilt", lengde: 5, setning: "Bilen stoppet fordi det var et rødt ___ i veikanten." },
            { ord: "skinke", lengde: 6, setning: "Jeg vil gjerne ha en brødskive med ___ og agurk." },
            { ord: "skylle", lengde: 6, setning: "Vi må ___ alle bærene godt før vi spiser dem." },
            { ord: "skjema", lengde: 6, setning: "Pappa måtte fylle ut et viktig ___ på datamaskinen." },
            { ord: "skive", lengde: 5, setning: "Jeg skar en tykk ___ av det nystekte brødet." },
            { ord: "skip", lengde: 4, setning: "Et kjempestort ___ seilte rolig inn mot havna." },
            { ord: "skifte", lengde: 6, setning: "Det er viktig å ___ til tørre sokker hvis du blir våt." },
            { ord: "skjeggete", lengde: 9, setning: "Sjørøverkapteinen var en skummel og ___ mann." },
            { ord: "sjalu", lengde: 5, setning: "Hunden ble litt ___ da katten la seg på fanget mitt." },
            { ord: "sjangle", lengde: 7, setning: "Isen var så glatt at vi begynte å ___ hit og dit." },
            { ord: "skimte", lengde: 6, setning: "Gjennom tåken kunne vi akkurat ___ omrisset av huset." },
            { ord: "sjenere", lengde: 7, setning: "Vi må skru ned lyden så vi ikke kommer til å ___ naboen." },
            { ord: "skipper", lengde: 7, setning: "En dyktig ___ styrte båten trygt gjennom de store bølgene." },
            { ord: "sjarm", lengde: 5, setning: "Den lille, lodne valpen hadde masse ___." },
            { ord: "skygge", lengde: 6, setning: "Da solen stekte som verst, satte vi oss i en sval ___." },
            { ord: "skyss", lengde: 5, setning: "Pappa var snill og ga oss ___ til bursdagen i dag." },
            { ord: "sjofel", lengde: 6, setning: "Å ødelegge leken for andre er en ___ oppførsel." },
            { ord: "skildre", lengde: 7, setning: "Forfatteren klarte å ___ den spennende skogen veldig godt." },
            { ord: "skikk", lengde: 5, setning: "Det er god ___ å si takk for maten når man er ferdig." },
            { ord: "skisse", lengde: 6, setning: "Maleren tegnet først en rask ___ med en grå blyant." },
            { ord: "sjokolade", lengde: 9, setning: "Vi fikk en bit mørk ___ etter middagen på lørdag." },
            { ord: "skingre", lengde: 7, setning: "Vi hørte en skarp og ___nde lyd fra den gamle fløyta." },
            { ord: "skylde", lengde: 6, setning: "Hvis man låner noe, må man huske å ikke ___ bort boka." },
            { ord: "skilpadde", lengde: 9, setning: "En grønn ___ svømte rolig rundt i det varme vannet." },
            { ord: "sjakt", lengde: 5, setning: "Gruvearbeiderne kjørte heis ned i en dyp ___." },
            { ord: "sjåfør", lengde: 6, setning: "En hyggelig ___ styrte den store bussen trygt." },
            { ord: "sjakal", lengde: 6, setning: "En sulten ___ listet seg forsiktig rundt på savannen." },
            { ord: "skifer", lengde: 6, setning: "Det gamle taket på hytta var dekket av grå ___." }
        ],
        "j-lyd": [
            { ord: "juli", lengde: 4, setning: "Det er midt på sommeren og veldig varmt i ___." },
            { ord: "jern", lengde: 4, setning: "Den tunge porten var laget av solid ___." },
            { ord: "jakt", lengde: 4, setning: "Katten snek seg rundt på ___ etter en mus." },
            { ord: "januar", lengde: 6, setning: "Årets aller første måned heter ___." },
            { ord: "jente", lengde: 5, setning: "Det begynte en ny ___ i klassen vår i dag." },
            { ord: "juni", lengde: 4, setning: "Skolen slutter og sommerferien starter i ___." },
            { ord: "jorde", lengde: 5, setning: "Traktoren kjørte rundt på et stort ___." },
            { ord: "jakke", lengde: 5, setning: "Husk å henge opp din ___ på knaggen din." },
            { ord: "jage", lengde: 4, setning: "Hunden prøvde å ___ fuglene vekk fra hagen." },
            { ord: "jeger", lengde: 5, setning: "En ___ gikk forsiktig gjennom skogen med hunden sin." },
            { ord: "hjerte", lengde: 6, setning: "Jeg kunne kjenne at mitt ___ slo raskt etter løpet." },
            { ord: "hjul", lengde: 4, setning: "Bilen punkterte og vi måtte bytte et ___." },
            { ord: "hjørne", lengde: 6, setning: "Butikken ligger rett rundt neste ___." },
            { ord: "hjem", lengde: 4, setning: "Etter en lang skoledag var det deilig å komme ___." },
            { ord: "hjelp", lengde: 5, setning: "Du må gjerne spørre om ___ hvis oppgaven er vanskelig." },
            { ord: "hjerne", lengde: 6, setning: "Vi bruker vår ___ til å tenke ut lure løsninger." },
            { ord: "juletre", lengde: 7, setning: "Vi pyntet et grønt og fint ___ med stjerne i toppen." },
            { ord: "jeg", lengde: 3, setning: "___ gleder meg skikkelig til det blir helg." },
            { ord: "juling", lengde: 6, setning: "I gamle dager var det vanlig at slemme folk fikk ___." },
            { ord: "jernbane", lengde: 8, setning: "Toget kjørte i stor fart bortover en lang ___." },
            { ord: "hjelpe", lengde: 6, setning: "Det er hyggelig å ___ hverandre med leksene." },
            { ord: "juks", lengde: 4, setning: "Å bruke hemmelige lapper på prøven kalles for ___." },
            { ord: "gjerde", lengde: 6, setning: "Sauen hoppet elegant over et lavt ___." },
            { ord: "gjette", lengde: 6, setning: "Klarer du å ___ hvem som gjemmer seg bak døra?" },
            { ord: "igjen", lengde: 5, setning: "Husk å lukke døra etter deg ___ når du går ut." },
            { ord: "gyte", lengde: 4, setning: "Om høsten svømmer laksen opp i elva for å ___." },
            { ord: "gifte", lengde: 5, setning: "Prinsen og prinsessen skulle ___ seg i den store kirken." },
            { ord: "gynge", lengde: 5, setning: "Det er gøy å ___ høyt på lekeplassen i friminuttet." },
            { ord: "gjemme", lengde: 6, setning: "Hvor skal du ___ deg hen når vi leker gjemsel?" },
            { ord: "hjort", lengde: 5, setning: "Vi fikk øye på en flott ___ som sto i skogkanten." },
            { ord: "hjelm", lengde: 5, setning: "Det er kjempeviktig å bruke ___ når man sykler." },
            { ord: "gjespe", lengde: 6, setning: "Gutten var så trøtt at han begynte å ___ høyt." },
            { ord: "gips", lengde: 4, setning: "Han brakk armen og måtte gå med en hvit ___." },
            { ord: "jordbær", lengde: 7, setning: "Om sommeren spiser vi røde ___ med fløte på." },
            { ord: "gjest", lengde: 5, setning: "Bestefar var en veldig hyggelig ___ i bursdagen min." },
            { ord: "jeksel", lengde: 6, setning: "Han kjente at en ny ___ var i ferd med å vokse frem." },
            { ord: "hjertelig", lengde: 9, setning: "Vi fikk en ___ velkomst da vi besøkte tante." },
            { ord: "jungel", lengde: 6, setning: "Det lever mange aper og tigre i den tette ___en." },
            { ord: "giftig", lengde: 6, setning: "Den røde soppen med hvite prikker er veldig ___." },
            { ord: "gyllen", lengde: 6, setning: "Hveten på åkeren hadde en vakker og ___ farge." }
        ],
        "ki/ky-lyd": [
            { ord: "kinn", lengde: 4, setning: "En tåre trillet sakte nedover hennes ___." },
            { ord: "kikker", lengde: 6, setning: "Gutten ___ spent ut av vinduet etter fugler." },
            { ord: "kino", lengde: 4, setning: "Vi kjøpte popcorn og så en gøy film på ___." },
            { ord: "kiosk", lengde: 5, setning: "De solgte kjempegod is i en liten ___ på stranda." },
            { ord: "kyss", lengde: 4, setning: "Mamma ga babyen et koselig ___ på pannen." },
            { ord: "kilo", lengde: 4, setning: "Posen med epler veide nøyaktig ett ___." },
            { ord: "kime", lengde: 4, setning: "Kirkeklokkene begynte å ___ høyt i tårnet." },
            { ord: "kyst", lengde: 4, setning: "Det ligger mange fine øyer langs norges ___." },
            { ord: "kikkert", lengde: 7, setning: "Kapteinen speidet langt av gårde med en ___." },
            { ord: "kyse", lengde: 4, setning: "Den lille babyen hadde en søt, hvit ___ på hodet." }
        ],
        "ski/sky-lyd": [
            { ord: "ski", lengde: 3, setning: "Om vinteren liker vi å gå på ___ i marka." },
            { ord: "skive", lengde: 5, setning: "Jeg smurte en ___ med deilig gulost til lunsj." },
            { ord: "skilt", lengde: 5, setning: "Bilen stoppet fordi det sto et rødt ___ ved veien." },
            { ord: "skinn", lengde: 4, setning: "Den varme vinterjakken var laget av ekte ___." },
            { ord: "skip", lengde: 4, setning: "Et enormt ___ seilte sakte inn den dype fjorden." },
            { ord: "skipper", lengde: 7, setning: "En gammel og erfaren ___ styrte skuta trygt i havn." },
            { ord: "sky", lengde: 3, setning: "En mørk ___ gjemte den varme solen bort fra oss." },
            { ord: "skyte", lengde: 5, setning: "Han prøvde å ___ på blink med pil og bue." },
            { ord: "skylle", lengde: 6, setning: "Husk å ___ eplet godt i kaldt vann før du spiser det." },
            { ord: "skygge", lengde: 6, setning: "Det var deilig å sitte i en sval ___ under treet." }
        ]
    },

    // === BLANDEDE LYDER OG FORVEKSLINGER ===
    "bolk5": {
        "gi/gy/ki/ky/ski/sky": [
            { ord: "gift", lengde: 4, setning: "Mamma og pappa har vært ___ i mange år." },
            { ord: "gynge", lengde: 5, setning: "Barna liker å ___ høyt opp mot skyene på lekeplassen." },
            { ord: "kyr", lengde: 3, setning: "Bonden hadde mange ___ som sto på den grønne enga." },
            { ord: "kinn", lengde: 4, setning: "Gutten ble rød på hvert ___ fordi han løp så fort." },
            { ord: "skilt", lengde: 5, setning: "Det sto et stort ___ som viste veien til byen." },
            { ord: "skyte", lengde: 5, setning: "Jeg skal prøve å ___ fotballen rett i mål." },
            { ord: "gikk", lengde: 4, setning: "Vi ___ en koselig tur rundt det lille vannet." },
            { ord: "skynde", lengde: 6, setning: "Vi må ___ oss så vi ikke kommer for sent til bussen." },
            { ord: "begynne", lengde: 7, setning: "Filmen skal ___ om nøyaktig to minutter." },
            { ord: "skinne", lengde: 6, setning: "Solen begynte endelig å ___ gjennom de mørke skyene." },
            { ord: "sjelden", lengde: 7, setning: "Det er veldig ___ at det snør midt på sommeren." },
            { ord: "sjette", lengde: 6, setning: "Storebror går nå i ___ klasse på skolen." },
            { ord: "kjole", lengde: 5, setning: "Hun hadde på seg en kjempefin, blå ___ på festen." },
            { ord: "kjøpe", lengde: 5, setning: "Jeg har spart lommepenger til å ___ et nytt spill." },
            { ord: "sjø", lengde: 3, setning: "Vi kastet stein ut i den store ___en fra brygga." },
            { ord: "sjef", lengde: 4, setning: "Pappa ble valgt til å være ___ på sin nye jobb." },
            { ord: "skjorte", lengde: 7, setning: "Han knappet igjen den øverste knappen på sin ___." },
            { ord: "sju", lengde: 3, setning: "Tallet som kommer etter seks, heter ___." },
            { ord: "kjøtt", lengde: 5, setning: "Vi grillet pølser laget av saftig ___." },
            { ord: "skjegg", lengde: 6, setning: "Nissen hadde et langt, krøllete og hvitt ___." }
        ],
        "Forveksling p/b/d": [
            { ord: "bro", lengde: 3, setning: "Bilen kjørte forsiktig over en smal ___." },
            { ord: "pus", lengde: 3, setning: "Vår lille ___ maler og koser seg på fanget." },
            { ord: "bur", lengde: 3, setning: "Undulaten fløy gladelig tilbake inn i sitt ___." },
            { ord: "brus", lengde: 4, setning: "I bursdagen fikk vi drikke rød ___ til pølsene." },
            { ord: "pose", lengde: 4, setning: "Han bar varene hjem i en stor ___." },
            { ord: "plan", lengde: 4, setning: "Vi la en veldig god ___ for hva vi skulle leke." },
            { ord: "banke", lengde: 5, setning: "Husk å ___ på døra før du går inn til noen." },
            { ord: "potte", lengde: 5, setning: "Mamma plantet en rød blomst i en fin ___." },
            { ord: "blyant", lengde: 6, setning: "Jeg må spisse min ___ før jeg kan tegne ferdig." },
            { ord: "bedøve", lengde: 6, setning: "Tannlegen måtte ___ tannen før han fikset den." },
            { ord: "bær", lengde: 3, setning: "Vi plukket en hel kurv med modne ___ i hagen." },
            { ord: "pelle", lengde: 5, setning: "Gutten fikk lov til å ___ opp skjell på stranda." },
            { ord: "pære", lengde: 5, setning: "Jeg spiste en saftig og grønn ___ til lunsj." },
            { ord: "denne", lengde: 5, setning: "Hvem har tegnet ___ utrolig fine tegningen?" },
            { ord: "bære", lengde: 5, setning: "Sekken var så tung at pappa måtte ___ den for meg." },
            { ord: "dunk", lengde: 4, setning: "Vi hørte et mystisk ___ fra rommet ved siden av." },
            { ord: "der", lengde: 3, setning: "Se på den fine fuglen som sitter ___ borte." },
            { ord: "brille", lengde: 6, setning: "Bestefar må bruke en ___ når han skal lese avisa." },
            { ord: "dum", lengde: 3, setning: "Den kjedelige feilen var i grunn ganske ___." },
            { ord: "på", lengde: 2, setning: "Husk å ta ___ deg jakka før du går ut." }
        ],
        "Forveksling k/g": [
            { ord: "ku", lengde: 2, setning: "En ___ tygget bedagelig på det grønne gresset." },
            { ord: "gå", lengde: 2, setning: "Nå må vi ___ raskt så vi rekker skolen." },
            { ord: "kam", lengde: 3, setning: "Han gredde det bustete håret med en blå ___." },
            { ord: "kål", lengde: 3, setning: "Bestemor puttet masse sunn ___ i gryteretten." },
            { ord: "gro", lengde: 3, setning: "Frøene trenger vann for å kunne ___ og bli store." },
            { ord: "garn", lengde: 4, setning: "Bestemor strikket votter av et mykt, rødt ___." },
            { ord: "krem", lengde: 4, setning: "Vi hadde deilig ___ på kakaoen vår." },
            { ord: "gale", lengde: 4, setning: "Han hørte hanen ___ tidlig om morgenen." },
            { ord: "gruppe", lengde: 6, setning: "Vi jobbet sammen i en liten ___ i timen." },
            { ord: "klasse", lengde: 6, setning: "Det er tjue elever i vår ___ på skolen." }
        ],
        "Forveksling f/v": [
            { ord: "vi", lengde: 2, setning: "I dag skal ___ dra på lekeplassen og kose oss." },
            { ord: "våt", lengde: 3, setning: "Genseren ble helt ___ etter at jeg falt i snøen." },
            { ord: "fra", lengde: 3, setning: "Jeg fikk en kjempefin gave ___ bestevennen min." },
            { ord: "ved", lengde: 3, setning: "Vi la en tørr kubbe med ___ på det varme bålet." },
            { ord: "furu", lengde: 4, setning: "Det sto en stor og gammel ___ i skogkanten." },
            { ord: "våge", lengde: 4, setning: "Du må ___ å prøve selv om det virker skummelt." },
            { ord: "frakk", lengde: 5, setning: "Mannen kledde på seg en lang, mørk ___ før han gikk." },
            { ord: "vinke", lengde: 5, setning: "Jeg pleier alltid å ___ til mamma fra vinduet." },
            { ord: "fryse", lengde: 5, setning: "Hvis du ikke har på votter, vil du ___ på hendene." },
            { ord: "vaske", lengde: 5, setning: "Det er viktig å ___ hendene godt før vi spiser mat." }
        ],
        "Forveksling t/d": [
            { ord: "duk", lengde: 3, setning: "Mamma la en fin, hvit ___ på det store middagsbordet." },
            { ord: "tak", lengde: 3, setning: "Lampen hang trygt ned fra rommets ___." },
            { ord: "toll", lengde: 4, setning: "Vi måtte stoppe ved grensen og kjøre gjennom en ___." },
            { ord: "dogg", lengde: 4, setning: "Om morgenen lå det fuktig ___ på det grønne gresset." },
            { ord: "tang", lengde: 4, setning: "Pappa brukte en kraftig ___ til å klippe av ståltråden." },
            { ord: "dråpe", lengde: 5, setning: "En enslig ___ med regn traff meg midt på nesen." },
            { ord: "dokke", lengde: 5, setning: "Jenta lekte med sin koselige ___ og trillet den i vogn." },
            { ord: "tønne", lengde: 5, setning: "Sjørøverne lagret drikkevann i en stor ___ av tre." },
            { ord: "tromme", lengde: 6, setning: "Gutten slo taktfast på en stor ___ i korpset." },
            { ord: "telefon", lengde: 7, setning: "Pappa snakket med bestefar i sin nye ___." }
        ]
    },

    // === STUMME BOKSTAVER ===
    "bolk6": {
        "Stum h": [
            { ord: "hva", lengde: 3, setning: "___ skal vi ha til middag i dag?" },
            { ord: "hvor", lengde: 4, setning: "___ har du lagt den blå blyanten min?" },
            { ord: "hvem", lengde: 4, setning: "___ er det som banker på døra vår?" },
            { ord: "hvilken", lengde: 7, setning: "___ av disse bøkene har du mest lyst til å lese?" },
            { ord: "hvorfor", lengde: 7, setning: "___ gråter den lille babyen?" },
            { ord: "hvordan", lengde: 7, setning: "___ klarte du å løse den vanskelige oppgaven?" },
            { ord: "hvit", lengde: 4, setning: "Snøen som falt i natt var helt ___ og ren." },
            { ord: "hvis", lengde: 4, setning: "Vi kan gå på lekeplassen ___ det slutter å regne." },
            { ord: "hverandre", lengde: 9, setning: "De to bestevennene pleier alltid å hjelpe ___." },
            { ord: "hver", lengde: 4, setning: "Vi pusser tennene både morgen og ___ kveld." }
        ],
        "Stum g": [
            { ord: "deilig", lengde: 6, setning: "Det var kjempe___ å bade i det varme vannet." },
            { ord: "dårlig", lengde: 6, setning: "Han ble hjemme fordi han var i ___ form." },
            { ord: "enig", lengde: 4, setning: "Barna ble til slutt ___ om hva de skulle leke." },
            { ord: "farlig", lengde: 6, setning: "Det er ___ å leke ute på den trafikkerte veien." },
            { ord: "ferdig", lengde: 6, setning: "Rop ut når du er ___ med den første oppgaven." },
            { ord: "giftig", lengde: 6, setning: "Vi må passe oss, for noen slanger har ___ bitt." },
            { ord: "lykkelig", lengde: 8, setning: "Jenta ble veldig ___ da hun fant igjen katten sin." },
            { ord: "heldig", lengde: 6, setning: "Du var sannelig ___ som vant hovedpremien i lotteriet." },
            { ord: "dyktig", lengde: 6, setning: "Maleren var utrolig ___ til å male fine bilder." },
            { ord: "modig", lengde: 5, setning: "Ridderen var veldig ___ og reddet hele slottet." },
            { ord: "nyttig", lengde: 6, setning: "En god ordbok er et ___ verktøy når man skriver." },
            { ord: "elendig", lengde: 7, setning: "Fotballaget spilte en ___ kamp og tapte stort." },
            { ord: "ærlig", lengde: 5, setning: "Det er alltid best å være ___ og tale sant." },
            { ord: "viktig", lengde: 6, setning: "Husk at det er ___ å spise en god frokost." },
            { ord: "riktig", lengde: 6, setning: "Svaret ditt på matteoppgaven var helt ___." },
            { ord: "umulig", lengde: 7, setning: "Det var nesten ___ å sykle opp den bratte bakken." },
            { ord: "dristig", lengde: 7, setning: "Det var et ___ hopp han tok fra den høye kanten." },
            { ord: "alvorlig", lengde: 8, setning: "Læreren så ___ på oss og ba oss lytte nøye." },
            { ord: "tydelig", lengde: 7, setning: "Du må snakke helt ___ så alle hører hva du sier." },
            { ord: "festlig", lengde: 7, setning: "Klovnen på sirkuset laget et veldig ___ show." },
            { ord: "prektig", lengde: 7, setning: "Kongen bodde i et ___ slott fullt av gull." },
            { ord: "misunnelig", lengde: 10, setning: "Han ble litt ___ da vennen fikk en ny sykkel." },
            { ord: "latterlig", lengde: 8, setning: "Det var en helt ___ og morsom historie du fortalte." },
            { ord: "samtidig", lengde: 8, setning: "De to løperne kom i mål nøyaktig ___." },
            { ord: "skyldig", lengde: 7, setning: "Tyven ble funnet ___ i å ha tatt pengene." },
            { ord: "tåpelig", lengde: 7, setning: "Å krangle om en liten leke er i grunn ganske ___." },
            { ord: "utrolig", lengde: 7, setning: "Det var et ___ flott fyrverkeri på nyttårsaften." },
            { ord: "herlig", lengde: 6, setning: "Det er en ___ og sval følelse å spise is i varmen." },
            { ord: "vennlig", lengde: 7, setning: "Den nye læreren hilste på oss med et ___ smil." },
            { ord: "underlig", lengde: 8, setning: "Vi hørte en ___ og mystisk lyd fra skogen." },
            { ord: "egentlig", lengde: 8, setning: "Hva har du ___ mest lyst til å gjøre i dag?" },
            { ord: "fryktelig", lengde: 9, setning: "Det ble et ___ uvær med torden og lyn i natt." },
            { ord: "hellig", lengde: 6, setning: "Kirken ble regnet som et gammelt og ___ sted." },
            { ord: "hjertelig", lengde: 9, setning: "Bestefar lo en ___ og høy felt opp fra hjertet." },
            { ord: "forsiktig", lengde: 9, setning: "Du må være ___ når du går over den glatte isen." },
            { ord: "kjedelig", lengde: 8, setning: "Det var en ___ oppgave, men jeg gjorde den ferdig." },
            { ord: "mulig", lengde: 5, setning: "Tror du det er ___ å bygge dette høye tårnet?" },
            { ord: "flittig", lengde: 7, setning: "Eleven jobbet ___ og konsentrert med boka si." },
            { ord: "rolig", lengde: 5, setning: "Hunden lå helt ___ i kurven sin og sov." }
        ],
        "Stum d": [
            { ord: "tid", lengde: 3, setning: "Vi har fortsatt god ___ før bussen kjører." },
            { ord: "gård", lengde: 4, setning: "Bonden bodde på en kjempefin ___ med mange dyr." },
            { ord: "god", lengde: 3, setning: "Maten mamma laget smakte veldig ___." },
            { ord: "bord", lengde: 4, setning: "Husk å sette glasset ditt ordentlig på det store ___et." },
            { ord: "glad", lengde: 4, setning: "Gutten ble utrolig ___ da han fikk en ny ball." },
            { ord: "hund", lengde: 4, setning: "En trofast ___ logret med halen og bjeffet muntert." },
            { ord: "hånd", lengde: 4, setning: "Eleven rakk opp en ___ for å svare på oppgaven." },
            { ord: "jorda", lengde: 5, setning: "Barna gravde en dyp grop ned i ___ med en spade." },
            { ord: "kaldt", lengde: 5, setning: "Det var så ___ ute at vannet i bøtta frøs til is." },
            { ord: "rundt", lengde: 5, setning: "Barna løp ___ og ___ på den grønne lekeplassen." },
            { ord: "strand", lengde: 5, setning: "Vi plukket fine skjell på en koselig ___ i sommer." },
            { ord: "tidlig", lengde: 6, setning: "Han måtte stå opp veldig ___ om morgenen." },
            { ord: "vind", lengde: 4, setning: "Det blåste en iskald ___ som rusket i trærne." },
            { ord: "sende", lengde: 5, setning: "Jeg skal ___ et koselig brev til mormor." },
            { ord: "vende", lengde: 5, setning: "Pappa måtte ___ bilen fordi vi kjørte feil." },
            { ord: "sider", lengde: 5, setning: "Den spennende boken hadde over hundre ___." },
            { ord: "side", lengde: 4, setning: "Du må tegne en fin tegning på den neste ___en." },
            { ord: "vide", lengde: 4, setning: "Fuglen fløy ut i den ___ og store verdenen." },
            { ord: "under", lengde: 5, setning: "Katten gjemte seg ___ den myke sofaen i stua." },
            { ord: "gjorde", lengde: 6, setning: "Eleven ___ leksene sine ferdig med en gang." }
        ],
        "gn-ord": [
            { ord: "agn", lengde: 3, setning: "Pappa satte en liten reke på kroken som ___." },
            { ord: "døgn", lengde: 4, setning: "Et helt ___ har nøyaktig tjuefire timer i seg." },
            { ord: "ligne", lengde: 5, setning: "Tvillingene var så like at de pleide å ___ hverandre." },
            { ord: "regne", lengde: 5, setning: "Læreren ba oss om å ___ ferdig de tre oppgavene." },
            { ord: "fregne", lengde: 6, setning: "Hun fikk en liten, søt ___ på nesen i sola." },
            { ord: "sagn", lengde: 4, setning: "Bestefar fortalte et gammelt ___ om et troll i fjellet." },
            { ord: "rogn", lengde: 4, setning: "Om høsten er det røde, fine bær på et ___detre." },
            { ord: "vogn", lengde: 4, setning: "Babyen lå og sov så søtt i sin fine ___." },
            { ord: "tegne", lengde: 5, setning: "Jeg har lyst til å ___ et stort slott med fargeblyanter." },
            { ord: "ugagn", lengde: 5, setning: "Den vesle valpen likte å gjøre litt ___ i hagen." }
        ],
        "nk/ng-ord": [
            { ord: "tenker", lengde: 6, setning: "Gutten sitter helt stille og ___ på en god løsning." },
            { ord: "hinker", lengde: 6, setning: "Jenta ___ bortover asfalten på bare ett ben." },
            { ord: "minke", lengde: 5, setning: "Hvis det slutter å regne, vil vannet i bekken ___." },
            { ord: "senket", lengde: 6, setning: "Kapteinen ___ det tunge ankeret ned i havet." },
            { ord: "lenke", lengde: 5, setning: "Hunden sto fast i en solid ___ av jern." },
            { ord: "hang", lengde: 4, setning: "Den fine jakken ___ trygt på knaggen sin." },
            { ord: "tang", lengde: 4, setning: "Det fløt mye grønn ___ i vannkanten på stranda." },
            { ord: "ting", lengde: 4, setning: "Han pakket alle sine ___ ned i den blå sekken." },
            { ord: "slang", lengde: 5, setning: "En lang og grønn ___ snek seg lydløst gjennom gresset." },
            { ord: "langt", lengde: 5, setning: "Det er veldig ___ å gå helt bort til butikken." }
        ]
    },

    // === PAR-ORD ===
    "bolk7": {
        "Par-ord": [
            { ord: "bake", lengde: 4, setning: "I dag skal vi ___ en kjempegod sjokoladekake." },
            { ord: "lesse", lengde: 5, setning: "Arbeiderne måtte ___ de tunge sekkene opp på lastebilen." },
            { ord: "hake", lengde: 4, setning: "Han støttet hodet sitt med en hånd under sin ___." },
            { ord: "tappe", lengde: 5, setning: "Vi kan ___ saft fra den store beholderen." },
            { ord: "bile", lengde: 4, setning: "I sommerferien skal vi ___ hele veien til bestefar." },
            { ord: "rekke", lengde: 5, setning: "Eleven måtte ___ opp hånden for å si noe." },
            { ord: "file", lengde: 4, setning: "Smeden måtte ___ på det skarpe jernet." },
            { ord: "felle", lengde: 5, setning: "De måtte ___ et stort tre som sto i veien." },
            { ord: "sete", lengde: 4, setning: "Han fant et ledig ___ langt bak på bussen." },
            { ord: "finne", lengde: 5, setning: "Kan du hjelpe meg med å ___ den mistede blyanten min?" },
            { ord: "lete", lengde: 4, setning: "Vi må ___ etter den røde lekebilen som ble borte." },
            { ord: "putte", lengde: 5, setning: "Kan du ___ alle brikkene tilbake i boksen?" },
            { ord: "bakke", lengde: 5, setning: "Sykkelen trillet kjempefort ned en bratt ___." },
            { ord: "lese", lengde: 4, setning: "Pappa skal ___ et koselig eventyr for meg." },
            { ord: "hakke", lengde: 5, setning: "En spettmeis pleier å ___ hull i barken på treet." },
            { ord: "tape", lengde: 4, setning: "Hun brukte gjennomsiktig ___ til å lime arket." },
            { ord: "bille", lengde: 5, setning: "En stor, svart ___ krøp forsiktig over stien." },
            { ord: "reke", lengde: 4, setning: "Til lunsj spiste bestefar et smørbrød med ___." },
            { ord: "fille", lengde: 5, setning: "Mamma tørket opp melkesølet med en ___." },
            { ord: "fele", lengde: 4, setning: "Gutten spilte en fin melodi på en gammel ___." },
            { ord: "sette", lengde: 5, setning: "Husk å ___ glasset ditt ordentlig på bordet." },
            { ord: "fine", lengde: 4, setning: "Barna plukket mange ___ blomster på enga." },
            { ord: "lette", lengde: 5, setning: "Fuglene var så ___ at de nesten ikke veide noe." },
            { ord: "pute", lengde: 4, setning: "Han la hodet sitt på en myk og deilig ___." },
            { ord: "fin", lengde: 3, setning: "Jenta hadde pyntet seg og var veldig ___." },
            { ord: "pen", lengde: 3, setning: "Hun tegnet en utrolig ___ tegning av et slott." },
            { ord: "penn", lengde: 4, setning: "Læreren rettet oppgaven med en rød ___." },
            { ord: "finn", lengde: 4, setning: "___ frem boka di og slå opp på side ti." },
            { ord: "gul", lengde: 3, setning: "Solen på himmelen var stor og ___." },
            { ord: "gull", lengde: 4, setning: "Kongen bar en tung krone laget av ekte ___." }
        ]
    },

    // === SMÅORD OG KORT O-LYD ===
    "bolk8": {
        "Viktige små-ord": [
            { ord: "til", lengde: 3, setning: "Vi skal gå ___ lekeplassen etter skolen." },
            { ord: "hun", lengde: 3, setning: "___ ble veldig glad da hun fikk gaven." },
            { ord: "hos", lengde: 3, setning: "I helgen skal jeg sove over ___ bestefar." },
            { ord: "nok", lengde: 3, setning: "Jeg tror vi har ___ mat til alle sammen." },
            { ord: "vel", lengde: 3, setning: "Du blir ___ med ut og leker i snøen?" },
            { ord: "skal", lengde: 4, setning: "Hva ___ vi gjøre i gymtimen i dag?" },
            { ord: "igjen", lengde: 5, setning: "Husk å lukke døra etter deg ___." },
            { ord: "han", lengde: 3, setning: "___ løp kjempefort og vant hele løpet." },
            { ord: "vil", lengde: 3, setning: "Hvem ___ ha det siste kakestykket?" },
            { ord: "rom", lengde: 3, setning: "Jenta ryddet det koselige ___met sitt helt selv." }
        ],
        "m ved slutten av ord": [
            { ord: "kam", lengde: 3, setning: "Han gredde det bustete håret sitt med en ___." },
            { ord: "tam", lengde: 3, setning: "Fuglen var så ___ at den spiste frø rett fra hånden." },
            { ord: "lam", lengde: 3, setning: "Om våren løper et lite ___ og hopper på enga." },
            { ord: "lem", lengde: 3, setning: "Katten smøg seg kjapt inn gjennom en åpen ___ på veggen." },
            { ord: "klem", lengde: 4, setning: "Jeg ga bestefar en god og varm ___ da han kom på besøk." },
            { ord: "kram", lengde: 4, setning: "Snøen var perfekt og ___, så vi kunne lage snømann." },
            { ord: "gram", lengde: 4, setning: "Et lite brev veier ikke mange ___." },
            { ord: "fram", lengde: 4, setning: "Hunden kom løpende ___ fra sitt gjemmested bak treet." },
            { ord: "slem", lengde: 4, setning: "Det er overhode ikke lov å være ___ mot andre." },
            { ord: "lom", lengde: 3, setning: "På vannet svømte en fargerik og vakker ___." }
        ],
        "Kort o-lyd": [
            { ord: "bukk", lengde: 4, setning: "De tre ___ene bruse skulle gå til seters for å gjøre seg fete." },
            { ord: "buksa", lengde: 5, setning: "Han fikk et lite hull på kneet i den nye ___ sin." },
            { ord: "dum", lengde: 3, setning: "Denne kjedelige feilen var i grunn litt ___." },
            { ord: "humle", lengde: 5, setning: "En stor og tykk ___ summet muntert rundt blomsten." },
            { ord: "klump", lengde: 5, setning: "Det var en stor ___ med leire på det hvite bordet." },
            { ord: "lukke", lengde: 5, setning: "Husk å ___ vinduet godt før det begynner å regne." },
            { ord: "lukte", lengde: 5, setning: "Vaflene begynte å ___ kjempegodt i hele huset." },
            { ord: "krum", lengde: 4, setning: "Bestefar ble litt ___ i ryggen da han ble eldre." },
            { ord: "nummer", lengde: 6, setning: "Hvilket ___ har du på fotballdrakten din?" },
            { ord: "plukke", lengde: 6, setning: "Vi liker å ___ skjell på den fine sandstranda." },
            { ord: "sukker", lengde: 6, setning: "Bestemor tok litt ___ på de rørte bærene." },
            { ord: "skuff", lengde: 5, setning: "Knivene og gafflene ligger øverst i en ___ på kjøkkenet." },
            { ord: "tung", lengde: 4, setning: "Den store sekken med stein var utrolig ___ å bære." },
            { ord: "krukke", lengde: 6, setning: "Det sto en gammel ___ med fine blomster på trappa." },
            { ord: "ung", lengde: 3, setning: "Valpen var fortsatt veldig ___ og likte å leke." },
            { ord: "tunge", lengde: 5, setning: "Rekker du å rekke ___ ut til meg?" },
            { ord: "dunk", lengde: 4, setning: "Vi hørte et høyt ___ fra kjelleren." },
            { ord: "ungen", lengde: 5, setning: "Fugle___ ga fra seg et lite pip fra reiret sitt." },
            { ord: "drukne", lengde: 6, setning: "Husk redningsvest så du ikke risikerer å ___ i vannet." },
            { ord: "skum", lengde: 4, setning: "Badekaret ble helt fullt av hvitt og boblende ___." }
        ],
        "Lang æ-lyd": [
            { ord: "klær", lengde: 4, setning: "Om vinteren må vi ta på oss varme ___." },
            { ord: "knær", lengde: 4, setning: "Han falt i skolegården og slo begge sine ___." },
            { ord: "tær", lengde: 3, setning: "Vi har fem ___ på hver fot." },
            { ord: "bær", lengde: 3, setning: "Om sommeren plukker vi søte ___ i skogen." },
            { ord: "være", lengde: 5, setning: "Vil du ___ med meg hjem og leke i dag?" },
            { ord: "pære", lengde: 5, setning: "Jeg spiste et grønt eple og en saftig ___." },
            { ord: "bære", lengde: 5, setning: "Sekken var så tung at pappa måtte ___ den." },
            { ord: "lære", lengde: 5, setning: "På skolen skal vi ___ å lese og skrive." },
            { ord: "trær", lengde: 4, setning: "Fuglene bygde reir i de høye ___ne." },
            { ord: "vært", lengde: 4, setning: "Hvor har du ___ i hele dag?" }
        ],
        "Kort u-lyd": [
            { ord: "humle", lengde: 5, setning: "En stor, lodden ___ summet muntert rundt blomsten." },
            { ord: "krukke", lengde: 6, setning: "Bestemor hadde en gammel ___ med drops på hylla." },
            { ord: "pung", lengde: 4, setning: "Sjørøveren gjemte gullmyntene i en liten ___ av skinn." },
            { ord: "tung", lengde: 4, setning: "Den store sekken med bøker var utrolig ___ å bære." },
            { ord: "slump", lengde: 5, setning: "Det var bare en ren ___ at vi møttes på butikken." },
            { ord: "bukt", lengde: 4, setning: "Skipet seilte inn i en lun ___ for å ligge i ro." },
            { ord: "blunke", lengde: 6, setning: "Klarer du å ___ med bare det ene øyet ditt?" },
            { ord: "jukse", lengde: 5, setning: "Det er ikke lov å ___ når vi spiller brettspill." },
            { ord: "plukke", lengde: 6, setning: "Om høsten liker vi å ___ deilige epler i hagen." },
            { ord: "lukte", lengde: 5, setning: "De nystekte vaflene begynte å ___ kjempegodt." }
        ]
    },

    // === LYDRETTE ORD ===
    "bolk9": {
        "lydrette_ord": [
            { ord: "le", lengde: 2, setning: "Det er gøy å ___ av en god vits." },
            { ord: "ri", lengde: 2, setning: "Kan jeg få ___ på hesten din?" },
            { ord: "tå", lengde: 2, setning: "Han slo en ___ borti bordbeinet." },
            { ord: "se", lengde: 2, setning: "Husk å ___ deg for i krysset." },
            { ord: "ro", lengde: 2, setning: "Vi må ___ båten helt inn til land." },
            { ord: "øy", lengde: 2, setning: "Vi kjørte båt ut til en ___." },
            { ord: "ti", lengde: 2, setning: "Etter ni kommer tallet ___." },
            { ord: "re", lengde: 2, setning: "Husk å ___ opp sengen din i dag." },
            { ord: "to", lengde: 2, setning: "Jeg har ___ grønne epler i vesken." },
            { ord: "do", lengde: 2, setning: "Jeg må på ___ for å vaske hendene." },
            { ord: "kø", lengde: 2, setning: "Det var lang ___ foran kassen." },
            { ord: "gå", lengde: 2, setning: "Skal vi ___ en tur i skogen?" },
            { ord: "bø", lengde: 2, setning: "Skremte jeg deg da jeg sa ___?" },
            { ord: "ål", lengde: 2, setning: "En ___ ser nesten ut som en slange." },
            { ord: "ur", lengde: 2, setning: "Bestefar har et gammelt ___ i lommen." },
            { ord: "te", lengde: 2, setning: "Vil du ha en kopp varm ___?" },
            { ord: "yr", lengde: 2, setning: "Det regner ikke mye, det er bare ___." },
            { ord: "en", lengde: 2, setning: "Jeg har bare ___ krone igjen." },
            { ord: "bæ", lengde: 2, setning: "Sauen sier ___ når den er sulten." },
            { ord: "by", lengde: 2, setning: "Oslo er en stor ___ i Norge." },
            { ord: "hi", lengde: 2, setning: "Bjørnen sover i et ___ om vinteren." },
            { ord: "ku", lengde: 2, setning: "En ___ kan gi oss god melk." },
            { ord: "fe", lengde: 2, setning: "I eventyret møtte hun en snill ___." },
            { ord: "is", lengde: 2, setning: "Det er godt med kald ___ om sommeren." },
            { ord: "ja", lengde: 2, setning: "Svarte du ___ eller nei på spørsmålet?" },
            { ord: "os", lengde: 2, setning: "Det ble mye ___ fra det svidde bålet." },
            { ord: "ni", lengde: 2, setning: "Katten har ___ liv, sies det." },
            { ord: "fy", lengde: 2, setning: "___, det var ikke pent gjort!" },
            { ord: "be", lengde: 2, setning: "Jeg vil ___ deg om en liten tjeneste." },
            { ord: "få", lengde: 2, setning: "Kan jeg ___ låne viskelæret ditt?" },
            { ord: "sy", lengde: 2, setning: "Mamma skal ___ en ny knapp på jakken." },
            { ord: "bål", lengde: 3, setning: "Vi tente et stort ___ i skogen." },
            { ord: "lim", lengde: 3, setning: "Bruk ___ for å feste arket." },
            { ord: "fil", lengde: 3, setning: "Snekkeren brukte en ___ på treverket." },
            { ord: "gås", lengde: 3, setning: "En stor ___ svømte rundt i dammen." },
            { ord: "hus", lengde: 3, setning: "Vi bor i et gult ___ med hage." },
            { ord: "lus", lengde: 3, setning: "Det er lurt å sjekke håret for ___." },
            { ord: "pil", lengde: 3, setning: "Buen skyter en ___ av gårde." },
            { ord: "mus", lengde: 3, setning: "En liten ___ spiste på osten." },
            { ord: "grå", lengde: 3, setning: "Himmelen ble helt ___ før det regnet." },
            { ord: "ide", lengde: 3, setning: "Jeg fikk en god ___ til tegningen min." },
            { ord: "klo", lengde: 3, setning: "Ørnen grep tak i greinen med en ___." },
            { ord: "pus", lengde: 3, setning: "Vår snille ___ liker å ligge på fanget." },
            { ord: "jul", lengde: 3, setning: "I desember feirer vi ___ i Norge." },
            { ord: "sol", lengde: 3, setning: "I dag skinner en varm ___ på himmelen." },
            { ord: "fem", lengde: 3, setning: "En hånd har ___ fingre totalt." },
            { ord: "sel", lengde: 3, setning: "En glatt ___ svømte i det kalde havet." },
            { ord: "mel", lengde: 3, setning: "Vi trenger ___ for å bake brød." },
            { ord: "nål", lengde: 3, setning: "Tråden må tres gjennom en spiss ___." },
            { ord: "bil", lengde: 3, setning: "Pappa kjører en blå ___ til jobben." },
            { ord: "dør", lengde: 3, setning: "Husk å lukke en ___ etter deg." },
            { ord: "mat", lengde: 3, setning: "Vi må spise sunn ___ hver dag." },
            { ord: "lam", lengde: 3, setning: "Et lite ___ hoppet rundt på engen." },
            { ord: "ris", lengde: 3, setning: "Vil du ha ___ eller poteter til middag?" },
            { ord: "arm", lengde: 3, setning: "Hun brakk en ___ da hun falt på isen." },
            { ord: "lys", lengde: 3, setning: "Tenn et ___ så det blir koselig." },
            { ord: "ufo", lengde: 3, setning: "Han trodde han så en ___ på himmelen." },
            { ord: "sal", lengde: 3, setning: "Rytteren la en ___ på hestens rygg." },
            { ord: "mor", lengde: 3, setning: "Min ___ er veldig snill med meg." },
            { ord: "mur", lengde: 3, setning: "Hagen har en gammel ___ av stein." },
            { ord: "lue", lengde: 3, setning: "Ta på en ___ så du ikke fryser." },
            { ord: "åre", lengde: 3, setning: "Båten manglet en ___ for å kunne ros." },
            { ord: "fly", lengde: 3, setning: "Vi skal ___ til syden i sommer." },
            { ord: "ost", lengde: 3, setning: "Jeg vil ha gul ___ på skiven min." },
            { ord: "ørn", lengde: 3, setning: "En stor ___ fløy høyt over fjellet." },
            { ord: "pai", lengde: 3, setning: "Bestemor bakte en deilig ___ med epler." },
            { ord: "hai", lengde: 3, setning: "En farlig ___ svømte dypt i havet." },
            { ord: "snu", lengde: 3, setning: "Vi måtte ___ fordi veien var stengt." },
            { ord: "syl", lengde: 3, setning: "Skomakeren brukte en ___ til skinnet." },
            { ord: "lyn", lengde: 3, setning: "Vi så et kraftig ___ på himmelen." },
            { ord: "fot", lengde: 3, setning: "Skoen passet akkurat til min ___." },
            { ord: "mål", lengde: 3, setning: "Spissen scoret et flott ___ på banen." },
            { ord: "løk", lengde: 3, setning: "Jeg må kutte en ___ til sausen." },
            { ord: "øye", lengde: 3, setning: "Hun fikk rusk i et ___ på turen." },
            { ord: "rot", lengde: 3, setning: "Treet har en dyp ___ i jorda." },
            { ord: "bro", lengde: 3, setning: "Bilen kjørte over en lang ___." },
            { ord: "blå", lengde: 3, setning: "Havet har en dyp ___ farge i dag." },
            { ord: "kne", lengde: 3, setning: "Han slo sitt ___ da han ramlet." },
            { ord: "lås", lengde: 3, setning: "Husk å sette ___ på sykkelen din." },
            { ord: "sur", lengde: 3, setning: "Sitronen smaker veldig ___ og frisk." },
            { ord: "far", lengde: 3, setning: "Min ___ liker å lese avisen på morgenen." },
            { ord: "ape", lengde: 3, setning: "En leken ___ klatret opp i treet." },
            { ord: "øre", lengde: 3, setning: "Hun hvisket noe hemmelig i mitt ___." },
            { ord: "due", lengde: 3, setning: "En hvit ___ satt på taket av huset." },
            { ord: "bie", lengde: 3, setning: "En ___ samlet honning fra blomsten." },
            { ord: "bok", lengde: 3, setning: "Jeg leser en spennende ___ på senga." },
            { ord: "ulv", lengde: 3, setning: "En grå ___ ulte mot månen i natt." },
            { ord: "sag", lengde: 3, setning: "Snekkeren brukte en ___ for å kappe planken." },
            { ord: "tre", lengde: 3, setning: "Fuglen bygde et rede i et høyt ___." },
            { ord: "rev", lengde: 3, setning: "En rød ___ snek seg rundt på gården." },
            { ord: "sil", lengde: 3, setning: "Hell vannet gjennom en ___ for å fjerne klumper." },
            { ord: "sko", lengde: 3, setning: "Jeg må knytte min ___ før vi løper." },
            { ord: "bær", lengde: 3, setning: "Vi fant søte ___ i skogkanten." },
            { ord: "elg", lengde: 3, setning: "En stor ___ sto midt i veien." },
            { ord: "øks", lengde: 3, setning: "Vedhoggeren brukte en ___ til kubbene." },
            { ord: "gul", lengde: 3, setning: "Sola tegnes ofte med en ___ farge." },
            { ord: "snø", lengde: 3, setning: "Det falt hvit ___ over hele landet." },
            { ord: "syv", lengde: 3, setning: "Uka har ___ dager totalt." },
            { ord: "kam", lengde: 3, setning: "Bruk en ___ til å ordne håret ditt." }
        ]
    },

    // === DE 100 VANLIGSTE ORD ===
    "bolk10": {
        "De 100 mest brukte": [
            { ord: "for", lengde: 3, setning: "Dette eplet er ___ stort til å ligge i lommen." },
            { ord: "og", lengde: 2, setning: "Gutt ___ jente lekte fint sammen i sandkassen." },
            { ord: "siden", lengde: 5, setning: "Det er lenge ___ vi spiste pølser sist." },
            { ord: "men", lengde: 3, setning: "Jeg vil gjerne leke, ___ jeg må spise middag først." },
            { ord: "ut", lengde: 2, setning: "Hunden ville gjerne ___ i den dype snøen." },
            { ord: "det", lengde: 3, setning: "Hvem er ___ som banker på døren min?" },
            { ord: "siste", lengde: 5, setning: "Dette var den ___ biten med kake som var igjen." },
            { ord: "seg", lengde: 3, setning: "Han snek ___ stille inn på kjøkkenet." },
            { ord: "sin", lengde: 3, setning: "Jenta passet godt på den nye sekken ___." },
            { ord: "slik", lengde: 4, setning: "Du må gjøre det ___ som læreren viser deg." },
            { ord: "som", lengde: 3, setning: "Hunden løp så fort ___ den bare klarte." },
            { ord: "kom", lengde: 3, setning: "Pappa ___ hjem med en stor pakke til oss." },
            { ord: "vil", lengde: 3, setning: "Jeg ___ gjerne ha et glass kald melk." },
            { ord: "denne", lengde: 5, setning: "Hvem har tegnet ___ fine tegningen på tavla?" },
            { ord: "mer", lengde: 3, setning: "Kan jeg få litt ___ saft i glasset mitt?" },
            { ord: "er", lengde: 2, setning: "Himmelen ___ helt blå og uten skyer i dag." },
            { ord: "tid", lengde: 3, setning: "Nå har vi god ___ til å gjøre leksene." },
            { ord: "vi", lengde: 2, setning: "I dag skal ___ spise pizza til middag." },
            { ord: "må", lengde: 2, setning: "Du ___ huske å vaske hendene før maten." },
            { ord: "mellom", lengde: 6, setning: "Katten la seg ___ de to myke putene." },
            { ord: "til", lengde: 3, setning: "Velkommen ___ bursdagen min på lørdag." },
            { ord: "sitt", lengde: 4, setning: "Barnet tegnet et hus på arket ___." },
            { ord: "ble", lengde: 3, setning: "Koppen falt i gulvet og ___ ødelagt." },
            { ord: "eller", lengde: 5, setning: "Vil du ha gult ___ rødt eple i dag?" },
            { ord: "første", lengde: 6, setning: "Dette var den ___ gangen jeg kjørte fly." },
            { ord: "en", lengde: 2, setning: "Jeg så ___ liten fugl som satt på gjerdet." },
            { ord: "dag", lengde: 3, setning: "I dag har vært en veldig fin ___ på skolen." },
            { ord: "ved", lengde: 3, setning: "Bordet står rett ___ det store vinduet." },
            { ord: "to", lengde: 2, setning: "Jeg har spist ___ hele brødskiver med ost." },
            { ord: "der", lengde: 3, setning: "Se på den store katten som sitter ___ borte." },
            { ord: "av", lengde: 2, setning: "Huset vårt er laget ___ røde mursteiner." },
            { ord: "norsk", lengde: 5, setning: "I dag lærte vi et nytt ___ ord på skolen." },
            { ord: "kan", lengde: 3, setning: "Hvem ___ hjelpe meg med å rydde opp?" },
            { ord: "opp", lengde: 3, setning: "Katten klatret raskt ___ i det høye treet." },
            { ord: "selv", lengde: 4, setning: "Jeg klarer å knytte skoene mine helt ___." },
            { ord: "på", lengde: 2, setning: "Boka ligger ___ den øverste hylla i skapet." },
            { ord: "kommer", lengde: 6, setning: "Bussen ___ alltid klokken åtte om morgenen." },
            { ord: "også", lengde: 4, setning: "Jeg vil ___ gjerne være med på leken." },
            { ord: "bli", lengde: 3, setning: "Vil du ___ med meg hjem etter skolen?" },
            { ord: "her", lengde: 3, setning: "Du kan sitte ___ ved siden av meg." },
            { ord: "at", lengde: 2, setning: "Hun fortalte ___ hun hadde fått en ny katt." },
            { ord: "alt", lengde: 3, setning: "Vi spiste opp ___ godteriet i skålen." },
            { ord: "skal", lengde: 4, setning: "Hva ___ vi gjøre i gymtimen i dag?" },
            { ord: "bare", lengde: 4, setning: "Det er ___ en uke igjen til ferien starter." },
            { ord: "hvor", lengde: 4, setning: "Vet du ___ jeg har lagt viskelæret mitt?" },
            { ord: "med", lengde: 3, setning: "Bli med ut for å leke ___ den nye ballen." },
            { ord: "hva", lengde: 3, setning: "Kan du gjette ___ jeg har i lommen min?" },
            { ord: "så", lengde: 2, setning: "Vi gikk på butikken, og ___ gikk vi hjem." },
            { ord: "få", lengde: 2, setning: "Det var veldig ___ barn på lekeplassen i dag." },
            { ord: "kroner", lengde: 6, setning: "Bollen på butikken kostet ti ___." },
            { ord: "de", lengde: 2, setning: "I går dro ___ på tur sammen i skogen." },
            { ord: "fikk", lengde: 4, setning: "Jeg ___ en kjempefin gave til bursdagen min." },
            { ord: "dette", lengde: 5, setning: "Hvem har laget ___ rotet på gulvet?" },
            { ord: "noe", lengde: 3, setning: "Har du lyst på ___ godt å spise?" },
            { ord: "nye", lengde: 3, setning: "Han viste frem de ___ skoene sine." },
            { ord: "når", lengde: 3, setning: "Vet du ___ skolen slutter i dag?" },
            { ord: "oss", lengde: 3, setning: "Vil du være med ___ å sparke fotball?" },
            { ord: "blir", lengde: 4, setning: "I morgen ___ det fint vær, har de sagt." },
            { ord: "nær", lengde: 3, setning: "Skolen vår ligger veldig ___ der vi bor." },
            { ord: "disse", lengde: 5, setning: "Hvem eier ___ vottene som ligger på benken?" },
            { ord: "har", lengde: 3, setning: "Jeg ___ to hunder og en liten katt." },
            { ord: "ta", lengde: 2, setning: "Husk å ___ på deg varme klær i dag." },
            { ord: "år", lengde: 2, setning: "I dag fyller jeg åtte ___ og skal feire." },
            { ord: "mot", lengde: 3, setning: "Bilen kjørte ___ den store røde garasjen." },
            { ord: "får", lengde: 3, setning: "Vi ___ besøk av bestefar i ettermiddag." },
            { ord: "den", lengde: 3, setning: "Hent ___ grønne bøtta som står ute." },
            { ord: "gang", lengde: 4, setning: "Dette var siste ___ jeg glemte matpakka." },
            { ord: "være", lengde: 5, setning: "Det er gøy å ___ sammen med gode venner." },
            { ord: "alle", lengde: 4, setning: "Nå må ___ barna sitte stille på plassen sin." },
            { ord: "nei", lengde: 3, setning: "Han svarte ___ da de spurte om han var trøtt." },
            { ord: "ikke", lengde: 4, setning: "Husk at det ___ er lov å løpe i gangen." },
            { ord: "jeg", lengde: 3, setning: "I dag har ___ lært å sykle uten støttehjul." },
            { ord: "noen", lengde: 4, setning: "Er det ___ som vet hvor veien går?" },
            { ord: "etter", lengde: 5, setning: "Vi skal spise is ___ at vi har spist mat." },
            { ord: "stor", lengde: 4, setning: "Vi så en kjempe ___ elg i skogen i dag." },
            { ord: "et", lengde: 2, setning: "Fuglen fløy opp på ___ høyt hustak." },
            { ord: "hadde", lengde: 5, setning: "I går ___ jeg en veldig morsom drøm." },
            { ord: "enn", lengde: 3, setning: "Søsteren min er to år eldre ___ meg." },
            { ord: "mye", lengde: 4, setning: "Det var ___ vann i den dype pytten." },
            { ord: "mange", lengde: 5, setning: "Det var ___ mennesker på butikken i dag." },
            { ord: "andre", lengde: 5, setning: "Dette er den ___ gangen jeg prøver dette." },
            { ord: "om", lengde: 2, setning: "Vi snakket ___ den morsomme filmen vi så." },
            { ord: "over", lengde: 4, setning: "Sola skinte fint ___ de høye fjellene." },
            { ord: "inn", lengde: 3, setning: "Gå ___ og sett deg i den varme stua." },
            { ord: "hans", lengde: 4, setning: "Guttens sykkel var blå, og hjelmen ___ var rød." },
            { ord: "går", lengde: 3, setning: "Vi ___ til skolen sammen hver eneste dag." },
            { ord: "fra", lengde: 3, setning: "Pakken jeg fikk var ___ bestemor og bestefar." },
            { ord: "da", lengde: 2, setning: "Vi var på skolen, og ___ ringte klokken ut." },
            { ord: "ha", lengde: 2, setning: "Jeg har lyst til å ___ en rød ball." },
            { ord: "sier", lengde: 4, setning: "Hva ___ læreren når timen begynner?" },
            { ord: "skulle", lengde: 6, setning: "Vi ___ egentlig på tur, men det regnet." },
            { ord: "var", lengde: 3, setning: "I går ___ vi på kino og så en film." },
            { ord: "uten", lengde: 4, setning: "Du kan ikke gå ut ___ å ha på jakke." },
            { ord: "kunne", lengde: 5, setning: "Jeg wished jeg ___ fly som en fugl." },
            { ord: "sine", lengde: 4, setning: "Han pakket alle lekene ___ ned i esken." },
            { ord: "ville", lengde: 5, setning: "Hunden ___ ikke komme inn da jeg ropte." },
            { ord: "han", lengde: 3, setning: "I dag tok ___ på seg den grønne genseren." },
            { ord: "vel", lengde: 3, setning: "Du har ___ husked å gjøre leksene dine?" },
            { ord: "under", lengde: 5, setning: "Katten gjemte seg ___ den store senga." },
            { ord: "hele", lengde: 4, setning: "Vi spiste opp ___ den store sjokoladen selv." }
        ]
    }
};

// Hjelpefunksjon: Hent alle ord flatt ut
function hentAlleOrd() {
    let alle = [];
    Object.values(ordlisteKategorier).forEach(bolk => {
        Object.values(bolk).forEach(liste => {
            alle = alle.concat(liste);
        });
    });
    return alle;
}

// Hjelpefunksjon: Filtrer ord basert på enten underkategori/bolk eller valgt lengde
function hentOrdFiltrert(kategoriValg, lengdeValg) {
    let baseOrd = [];

    if (kategoriValg === "alle") {
        baseOrd = hentAlleOrd();
    } else {
        // Søk gjennom alle bolker for å finne den spesifikke kategorien
        for (const bolkKey in ordlisteKategorier) {
            if (ordlisteKategorier[bolkKey][kategoriValg]) {
                baseOrd = ordlisteKategorier[bolkKey][kategoriValg];
                break;
            }
        }
    }

    if (lengdeValg !== "alle") {
        const målLengde = parseInt(lengdeValg, 10);
        baseOrd = baseOrd.filter(item => item.ord.length === målLengde);
    }

    // Returner kun ord-strengene (i versaler for rutenettet)
    return baseOrd.map(item => item.ord.toUpperCase());
}